experiment_name: "irmas_single_label_mel_densenet"
task_mode: "single_label"
dataset: "irmas"
feature_mode: "mel"

model:
  backbone: "cnn_densenet_121"
  dropout: 0.3
  pretrained_weights: ""

training:
  epochs: 50
  batch_size: 32
  learning_rate: 0.0003
  weight_decay: 0.0001
  val_frac: 0.2
  use_spec_augment: false
  loss_function: "standard"
  patience: 10
  num_workers: 4
  seed: 1337
  mixed_precision: true